name: CI

on: push

jobs:
  ci:
    name: Client tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run test
      - run: npm run build
