name: Deploy

on: 
  workflow_run:
    workflows:
      - "CI"
    branches:
      - "main"
      - "master"
    types:
      - completed

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
